### ISSUE TITLE
Practica Interfaz Grafica en Visual Studio

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-topic-avanza4usssss#1]
[PRACTICA 2_REPORTE VISUAL STUDIO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-topic-avanza4usssss/files/10761975/PRACTICA.2_REPORTE.VISUAL.STUDIO.pdf)

**Comment by yanet02** [comment]
-Portada Excelente : muy creativa (25 puntos) 
-Procedimiento: (22 puntos): Faltó describir materiales.
-Figuras, ilustraciones y fotografías ( 17 puntos)Faltaron más figuras de la práctica..
-Resultados y conclusiones: (MUY BIEN) 25 puntos 
Total : 89 de 100.
Calificación: 17.8 % de 20%.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
